### ISSUE TITLE
Numbers for the whole country

### ISSUE THREAD

**Issue by bhessen** [thebino/rki_covid#22]
Hi, is it possible to get sensors for the numbers for the whole of Germany, not only for different districts?

Thanks, Ben

**Comment by thebino** [comment]
Pleasu use the default integration for country sensors: https://www.home-assistant.io/integrations/coronavirus/

**Comment by bhessen** [comment]
I do use the default integration, but this uses Johns Hopkins University data which does not match directly to the 'official' RKI data used in Germany. Therefore, RKI data for the whole of Germany would be nice, imo.

**Comment by thebino** [comment]
There is already an integration for whole Germany. Unfortunately you have to look for "**Deutschland**" in the list of districts since the districts and states are not translated.

<img width="416" alt="rki_germany" src="https://user-images.githubusercontent.com/841681/107618207-7cfc6a80-6c51-11eb-9168-e63c0145f5d7.png">

**Comment by bhessen** [comment]
Ah, I didn't see that. Thanks a lot! Exactly what I was looking for.
