### ISSUE TITLE
Feature Request: Enable use of "Statistics Graph" card

### ISSUE THREAD

**Issue by lacalamine64** [thebino/rki_covid#67]
Hi @thebino,

thanks for your awesome integration.

I would like to ask for one feature: I tried to use the "Statistics Graph" card but couldn't select one of your integration's entities. At the bottom of the list was a link to this page:
[https://www.home-assistant.io/more-info/statistics/](https://www.home-assistant.io/more-info/statistics/)

Is it possible for you to enable that? The "Statistics Graph" card has the option to show columns, what I would like to use.

Regards,
Stephan

**Comment by matze338** [comment]
bump 😇

**Comment by thebino** [comment]
Its working on my side for weeks, please re-check.
<img width="497" alt="Screenshot 2022-02-14 at 02 27 56" src="https://user-images.githubusercontent.com/841681/153785360-653c93d0-1f60-4e7a-80a8-fa45226d3297.png">


```
- platform: statistics
  name: "Bayern Week incidence over last year"
  entity_id: sensor.bl_bayern_weekincidence
  state_characteristic: mean
```

**Comment by matze338** [comment]
@thebino You using a separate integration (platform: statistics). Its generate a new sensor entity which is statistic graph compatible. For sure it works but you need separate yaml code for each rki sensor.

For example the thermal Comfort integration done this in there own integration platform: https://github.com/dolezsa/thermal_comfort/issues/74

So all sensors from the integration (rki covid numbers) can integrate this feature by his own too, so that you do not need an extra integration with addtitional sensor entities.

**Comment by thebino** [comment]
@matze338 This was already part of my integration as well: https://github.com/thebino/rki_covid/blob/master/custom_components/rki_covid/sensor.py#L162
as recommended in the [official documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
